nginx:
    build: nginx
    ports:
        - "8000:80"
    links:
        - server1
        - server2

server1:
    build: server1

server2:
    build: server2

dbServer:
    image: percona/percona-server:8.0
    environment: 
    - MYSQL_ROOT_PASSWORD=root

